framework:
    messenger:

        transports:
            events:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/events'
                options:
                    exchange:
                        name: events
                        type: direct
                    queues:
                        'events.shard.0':
                            binding_keys: [ 'shard.0' ]
                            arguments:
                                x-single-active-consumer: true

                        'events.shard.1':
                            binding_keys: [ 'shard.1' ]
                            arguments:
                                x-single-active-consumer: true

                        'events.shard.2':
                            binding_keys: [ 'shard.2' ]
                            arguments:
                                x-single-active-consumer: true

                        'events.shard.3':
                            binding_keys: [ 'shard.3' ]
                            arguments:
                                x-single-active-consumer: true

        routing:
            App\Bus\Event\EventMessage: events
